name: Slack Notification Action
description: "Send notifications to Slack based on GitHub events"
runs:
  using: "node20"
  main: "index.js"
inputs:
  SLACK_TOKEN:
    description: "Slack token"
    required: true
  GITHUB_TOKEN:
    description: "Github token"
    required: true
  ACTION_TYPE:
    description: "Action Type"
    required: true
  EC2_NAME:
    description: "EC2 name"
    required: false
  IMAGE_TAG:
    description: "Image tag"
    required: false
  JOB_STATUS:
    description: "Job status"
    required: false
