name: Slack Notification Action
description: "Send notifications to Slack based on GitHub events"
runs:
  using: "node20"
  main: "index.js"
inputs:
  SLACK_TOKEN:
    description: "slack token"
    required: true
  GITHUB_TOKEN:
    description: "github token"
    required: true
  ACTION_TYPE:
    description: "github token"
    required: true
